import type { Finding } from '@cfa/core';
// Only the scoring module: the pane doesn't need the parser or the rules.
import { scoreFindings, type Score, type ScoredCategory } from '@cfa/core/scoring';
import type { PaneFinding, PaneResult } from '../shared/pane-result.ts';

/** Stable key of a finding within a flow, used to remember dismissals. */
export function findingKey(finding: PaneFinding): string {
  return `${finding.ruleId}|${finding.target.path.join('/') || 'flow'}`;
}

/** The flow's score without the dismissed findings (same formula as the analysis). */
export function scoreWithout(result: PaneResult, dismissed: ReadonlySet<string>): Score {
  return scoreFindings(result.findings as unknown as Finding[], (f) =>
    dismissed.has(findingKey(f as unknown as PaneFinding)),
  );
}

export function formatDuration(ms: number): string {
  if (ms < 1000) return `${Math.round(ms)} ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)} s`;
  if (ms < 3_600_000) return `${(ms / 60_000).toFixed(1)} min`;
  return `${(ms / 3_600_000).toFixed(1)} h`;
}

const SEVERITY = { high: 'High', medium: 'Medium', low: 'Low' } as const;

export const CAPPED_NOTE = 'capped at C while a high security finding is open';

export const CATEGORY_LABELS: [ScoredCategory, string][] = [
  ['speed', 'Speed'],
  ['resources', 'Resources'],
  ['reliability', 'Reliability'],
  ['security', 'Security'],
];

/** The analysis as Markdown, for pasting into a ticket, a chat or a review. */
export function markdownReport(result: PaneResult, dismissed: ReadonlySet<string>): string {
  const score = scoreWithout(result, dismissed);
  const open = result.findings.filter((f) => !dismissed.has(findingKey(f)));
  const lines = [
    `# Flow analysis: ${result.displayName}`,
    '',
    [
      `**Grade ${score.grade}** (${score.overall}/100${score.capped ? `, ${CAPPED_NOTE}` : ''})`,
      ...CATEGORY_LABELS.map(([category, name]) => `${name} ${score.categories[category].score}`),
    ].join(' · '),
    `${result.actionCount} actions · about ${result.estimate.total.toLocaleString('en-US')} actions per run${result.estimate.assumed ? ' (estimated)' : result.runs ? ' (from runs)' : ''} · analysed ${result.analysedAt.slice(0, 10)}`,
    '',
  ];
  const runs = result.runs;
  if (runs && runs.sampled > 0) {
    const statuses = Object.entries(runs.statuses)
      .map(([status, count]) => `${count} ${status.toLowerCase()}`)
      .join(', ');
    lines.push(
      `**Recent runs:** ${runs.sampled} (${statuses}) · median ${formatDuration(runs.durationP50Ms)} · slowest 5% ${formatDuration(runs.durationP95Ms)}`,
      '',
    );
    for (const item of runs.slowest) {
      const time =
        item.timeSharePct !== undefined
          ? `${item.timeSharePct}% of the run, ${formatDuration(item.busyP50Ms)}`
          : `${formatDuration(item.busyP50Ms)} over ${item.executionsPerRun ?? 1} executions`;
      lines.push(`- ${item.targetLabel}: ${time}`);
    }
    for (const loop of runs.loops) {
      lines.push(
        `- ${loop.targetLabel}: ${loop.iterationsP50}${loop.truncated ? '+' : ''} items${loop.nested ? ' per outer item' : ''} (max ${loop.iterationsMax})`,
      );
    }
    lines.push('');
  }
  if (open.length === 0) lines.push('No open findings.');
  for (const f of open) {
    lines.push(
      `## ${SEVERITY[f.severity]} · ${f.ruleId} ${f.title}`,
      '',
      `**Where:** ${f.targetLabel}`,
      '',
      f.message,
      '',
      `**Fix:** ${f.fix}`,
      '',
    );
  }
  const hidden = result.findings.length - open.length;
  if (hidden > 0)
    lines.push(`_${hidden} dismissed finding${hidden === 1 ? '' : 's'} not shown._`, '');
  lines.push('_Generated by Cloud Flow Analyzer._');
  return lines.join('\n');
}
