import type { Finding } from '@cfa/core';
// Only the scoring module: the pane doesn't need the parser or the rules.
import { scoreFindings, type Score } from '@cfa/core/scoring';
import type { PaneFinding, PaneResult } from '../shared/pane-result.ts';

/** Stable key of a finding within a flow, used to remember dismissals. */
export function findingKey(finding: PaneFinding): string {
  return `${finding.ruleId}|${finding.target.path.join('/') || 'flow'}`;
}

/** The flow's score without the dismissed findings (same formula as the analysis). */
export function scoreWithout(result: PaneResult, dismissed: ReadonlySet<string>): Score {
  return scoreFindings(result.findings as unknown as Finding[], (f) =>
    dismissed.has(findingKey(f as unknown as PaneFinding)),
  );
}

const SEVERITY = { high: 'High', medium: 'Medium', low: 'Low' } as const;

/** The analysis as Markdown, for pasting into a ticket, a chat or a review. */
export function markdownReport(result: PaneResult, dismissed: ReadonlySet<string>): string {
  const score = scoreWithout(result, dismissed);
  const open = result.findings.filter((f) => !dismissed.has(findingKey(f)));
  const lines = [
    `# Flow analysis: ${result.displayName}`,
    '',
    `**Grade ${score.grade}** (${score.overall}/100) · Speed ${score.categories.speed.score} · Resources ${score.categories.resources.score} · Reliability ${score.categories.reliability.score}`,
    `${result.actionCount} actions · about ${result.estimate.total.toLocaleString('en-US')} actions per run${result.estimate.assumed ? ' (estimated)' : ''} · analysed ${result.analysedAt.slice(0, 10)}`,
    '',
  ];
  if (open.length === 0) lines.push('No open findings.');
  for (const f of open) {
    lines.push(
      `## ${SEVERITY[f.severity]} · ${f.ruleId} ${f.title}`,
      '',
      `**Where:** ${f.targetLabel}`,
      '',
      f.message,
      '',
      `**Fix:** ${f.fix}`,
      '',
    );
  }
  const hidden = result.findings.length - open.length;
  if (hidden > 0)
    lines.push(`_${hidden} dismissed finding${hidden === 1 ? '' : 's'} not shown._`, '');
  lines.push('_Generated by Cloud Flow Analyzer._');
  return lines.join('\n');
}
